export const storeCategories = [
  'Whisky', 'Wine', 'Champagne', 'Cognac', 'Brandy',
  'Gin', 'Liqueur', 'Rum', 'Tequila', 'Vodka',
  'Ciders', 'Spirits', 'Scotch'
];

export const accessoryCategories = {
  'Glassware': [
    'Beer Glass',
    'Wine Glasses',
    'Champagne Glasse',
    'Red Wine Glasses'
  ],
  'Drinkware': [
    'Carafes & Decanters',
    'Highball Glasses',
    'Bulk Glassware',
    'Zombie Glasses',
    'Gin Glasses',
    'Whiskey Glasses',
    'White Wine Glasses'
  ]
};

export const products = [
  {
    id: 1,
    slug: 'lady-eclipse',
    name: 'Lady Eclipse',
    fullName: 'Lady Eclipse Chocolate Orange Liqueur 750 ML',
    category: 'Small-batch liqueur',
    origin: 'South Africa',
    price: 'R850',
    image: '/assets/products/lady-eclipse.png',
    badge: 'Just in',
    brand: 'Lady Eclipse',
    size: '750 ML',
    sku: 'BWSLE001',
    description: 'A velvety chocolate-and-orange liqueur with a rich, smooth finish. Serve it neat, over ice or alongside dessert.',
    details: { style: 'Chocolate orange liqueur', region: 'South Africa', serve: 'Neat or over ice' },
  },
  {
    id: 2,
    slug: 'glenmorangie-single-malt-scotch-whiskey-15-year-old-750ml',
    name: 'Glenmorangie 15 Year Old',
    fullName: 'Glenmorangie Single Malt Scotch Whisky 15 Year Old 750 ML',
    category: 'Single malt Scotch whisky',
    origin: 'Highlands, Scotland',
    price: 'R929',
    image: '/assets/products/glenmorangie-15.png',
    badge: 'Limited',
    brand: 'Glenmorangie',
    size: '750 ML',
    sku: 'GS-GM15-750',
    description: 'An elegant Highland single malt with layers of orchard fruit, honeyed malt and gentle oak.',
    details: { style: 'Single malt Scotch', region: 'Highlands, Scotland', age: '15 years' },
  },
  {
    id: 3,
    slug: 'bowmore-12-year-old-islay-single-malt-scotch-whisky-750-ml',
    name: 'Bowmore 12 Year Old',
    fullName: 'Bowmore 12 Year Old Islay Single Malt Scotch Whisky 750 ML',
    category: 'Whisky',
    origin: 'Islay, Scotland',
    price: 'R699',
    image: '/assets/products/bowmore-12.png',
    badge: 'Cellar pick',
    brand: 'Bowmore',
    size: '750 ML',
    sku: 'GSNGF00101',
    options: ['Pack of 1'],
    description: 'A classic Islay single malt that balances coastal smoke with citrus sweetness. Twelve years in bourbon and sherry casks create a smooth, layered and quietly complex whisky.',
    gallery: [
      '/assets/products/bowmore-gallery-1.png',
      '/assets/products/bowmore-gallery-2.png',
      '/assets/products/bowmore-gallery-3.png',
    ],
    details: {
      style: 'Peated single malt',
      region: 'Islay, Scotland',
      age: '12 years',
      maturation: 'Bourbon & sherry casks',
      weight: '1.5 kg',
      dimensions: '80 Ã 80 Ã 320 mm',
    },
    tags: ['Island Single Malt', 'Bowmore', '12 Year'],
  },
  {
    id: 4,
    slug: 'the-irishman-harvest-single-malt-750ml',
    name: 'The Irishman Harvest',
    fullName: 'The Irishman Harvest Single Malt 750 ML',
    category: 'Irish whiskey',
    origin: 'County Carlow, Ireland',
    price: 'R569',
    image: '/assets/products/irishman-harvest.png',
    badge: 'New vintage',
    brand: 'The Irishman',
    size: '750 ML',
    sku: 'GS-IH-750',
    description: 'An approachable Irish whiskey with ripe fruit, warm spice and a soft, rounded finish.',
    details: { style: 'Irish whiskey', region: 'County Carlow, Ireland', serve: 'Neat or over ice' },
  },
  {
    id: 5,
    slug: 'loch-lomond-single-malt-scotch-whisky-750-ml',
    name: 'Loch Lomond Single Malt',
    fullName: 'Loch Lomond Single Malt Scotch Whisky 750 ML',
    category: 'Single malt Scotch whisky',
    origin: 'Highlands, Scotland',
    price: 'R819',
    image: '/assets/products/loch-lomond.png',
    badge: 'Sommelier pick',
    brand: 'Loch Lomond',
    size: '750 ML',
    sku: 'GS-LL-750',
    description: 'A balanced Highland malt with citrus, toasted cereal and a restrained touch of smoke.',
    details: { style: 'Single malt Scotch', region: 'Highlands, Scotland', serve: 'Neat or with water' },
  },
  {
    id: 6,
    slug: 'jose-cuervo-reserva-de-la-familia-750ml',
    name: 'Jose Cuervo Reserva de la Familia',
    fullName: 'Jose Cuervo Reserva de la Familia Extra AÃ±ejo 750 ML',
    category: 'Tequila',
    origin: 'Jalisco, Mexico',
    price: 'R2999',
    image: '/assets/products/tequila/jose-cuervo-reserva.png',
    badge: 'Rare release',
    brand: 'Jose Cuervo',
    size: '750 ML',
    sku: 'GS-TQ-JC-750',
    featured: false,
    description: 'A patient extra aÃ±ejo with deep oak, toasted almond, vanilla and warming spice, made for unhurried sipping.',
    details: { style: 'Extra aÃ±ejo', region: 'Jalisco, Mexico', maturation: 'French & American oak' },
  },
  {
    id: 7,
    slug: '1800-cristalino-anejo-750ml',
    name: '1800 Cristalino AÃ±ejo',
    fullName: '1800 Cristalino AÃ±ejo Tequila 750 ML',
    category: 'Tequila',
    origin: 'Jalisco, Mexico',
    price: 'R1499',
    image: '/assets/products/tequila/1800-cristalino.png',
    badge: 'Cristalino',
    brand: '1800 Tequila',
    size: '750 ML',
    sku: 'GS-TQ-1800-750',
    featured: false,
    description: 'An oak-aged aÃ±ejo refined to crystalline clarity, with vanilla, citrus and a smooth, polished finish.',
    details: { style: 'Cristalino aÃ±ejo', region: 'Jalisco, Mexico', agave: '100% blue Weber' },
  },
  {
    id: 8,
    slug: 'codigo-1530-reposado-tequila-750ml',
    name: 'CÃ³digo 1530 Reposado',
    fullName: 'CÃ³digo 1530 Reposado Tequila 750 ML',
    category: 'Tequila',
    origin: 'AmatitÃ¡n, Mexico',
    price: 'R1159',
    image: '/assets/products/tequila/codigo-reposado.png',
    badge: 'Estate agave',
    brand: 'CÃ³digo 1530',
    size: '750 ML',
    sku: 'GS-TQ-C1530R-750',
    featured: false,
    description: 'A composed reposado balancing cooked agave with vanilla, caramel and elegant French-oak spice.',
    details: { style: 'Reposado', region: 'AmatitÃ¡n, Mexico', maturation: 'French white oak' },
  },
  {
    id: 9,
    slug: 'casamigos-reposado-750ml',
    name: 'Casamigos Reposado',
    fullName: 'Casamigos Reposado Tequila 750 ML',
    category: 'Tequila',
    origin: 'Jalisco, Mexico',
    price: 'R939',
    image: '/assets/products/tequila/casamigos-reposado.png',
    badge: 'House favourite',
    brand: 'Casamigos',
    size: '750 ML',
    sku: 'GS-TQ-CASA-750',
    featured: false,
    description: 'Silky reposado tequila with softly toasted oak, caramel and cocoa wrapped around sweet agave.',
    details: { style: 'Reposado', region: 'Jalisco, Mexico', maturation: 'American white oak' },
  },
  {
    id: 10,
    slug: 'codigo-1530-rosa-tequila-750ml',
    name: 'CÃ³digo 1530 Rosa',
    fullName: 'CÃ³digo 1530 Rosa Tequila 750 ML',
    category: 'Tequila',
    origin: 'AmatitÃ¡n, Mexico',
    price: 'R929',
    image: '/assets/products/tequila/codigo-rosa.png',
    badge: 'Rosa',
    brand: 'CÃ³digo 1530',
    size: '750 ML',
    sku: 'GS-TQ-C1530ROSA-750',
    featured: false,
    description: 'A naturally blushed tequila rested in Cabernet-seasoned oak for delicate floral fruit and bright agave.',
    details: { style: 'Rosa', region: 'AmatitÃ¡n, Mexico', maturation: 'Cabernet-seasoned oak' },
  },
  {
    id: 11,
    slug: 'meukow-vs-de-luxe-750-ml',
    name: 'Meukow VS De Luxe',
    fullName: 'Meukow VS De Luxe Cognac 750 ML',
    category: 'Brandy',
    origin: 'Cognac, France',
    price: 'R539',
    image: '/assets/products/brandy/meukow-vs-de-luxe.png',
    badge: 'French classic',
    brand: 'Meukow',
    size: '750 ML',
    sku: 'GS-BR-MKVS-750',
    featured: false,
    options: ['Single bottle'],
    description: 'A supple VS cognac with ripe fruit, vanilla and toasted oak, presented with Meukowâs distinctive feline character.',
    details: { style: 'VS Cognac', region: 'Cognac, France', serve: 'Neat or in a classic cocktail' },
    tags: ['Brandy', 'Cognac', 'VS'],
  },
  {
    id: 12,
    slug: 'kwv-brandy-pack-of-6-750-ml',
    name: 'KWV Brandy Pack of 6',
    fullName: 'KWV Brandy Pack of 6 Ã 750 ML',
    category: 'Brandy',
    origin: 'Paarl, South Africa',
    price: 'R1290',
    image: '/assets/products/brandy/kwv-brandy-pack.png',
    badge: 'Case selection',
    brand: 'KWV',
    size: '6 Ã 750 ML',
    sku: 'GS-BR-KWV6-750',
    featured: false,
    options: ['Case of 6'],
    description: 'A generous six-bottle case of smooth South African brandy with dried fruit, caramel and softly warming spice.',
    details: { style: 'Blended brandy', region: 'Paarl, South Africa', pack: '6 bottles' },
    tags: ['Brandy', 'KWV', 'Case'],
  },
  {
    id: 13,
    slug: 'kwv-20-year-old-750-ml',
    name: 'KWV 20 Year Old',
    fullName: 'KWV 20 Year Old Potstill Brandy 750 ML',
    category: 'Brandy',
    origin: 'Paarl, South Africa',
    price: 'R1919',
    image: '/assets/products/brandy/kwv-20-year-old.png',
    badge: '20 years',
    brand: 'KWV',
    size: '750 ML',
    sku: 'GSNGFWK0093',
    featured: false,
    options: ['Single bottle'],
    description: 'A celebrated luxury potstill brandy, matured for at least twenty years for exceptional depth, oak polish and lingering dried fruit.',
    details: { style: 'Potstill brandy', region: 'Paarl, South Africa', age: '20 years', maturation: 'French oak' },
    tags: ['Brandy', 'South African Brandy', '20 Year'],
  },
  {
    id: 14,
    slug: 'avante-founders-xv-in-cabinet-cape-brandy-750-ml',
    name: 'Avante Foundersâ XV',
    fullName: 'Avante Foundersâ XV in Cabinet Cape Brandy 750 ML',
    category: 'Brandy',
    origin: 'Western Cape, South Africa',
    price: 'R2405',
    image: '/assets/products/brandy/avante-founders-xv.png',
    badge: 'Cabinet edition',
    brand: 'Avante',
    size: '750 ML',
    sku: 'GS-BR-AVXV-750',
    featured: false,
    options: ['Cabinet edition'],
    description: 'A fifteen-year Cape brandy with peach, dried apricot and pear, followed by honeyed richness and a long walnut-and-vanilla finish.',
    details: { style: 'Cape potstill brandy', region: 'Western Cape, South Africa', age: '15 years', maturation: 'French & American oak' },
    tags: ['Brandy', 'Cape Brandy', 'Founders XV'],
  },
  {
    id: 15,
    slug: 'rust-en-vrede-estate-potstill-brandy-750ml',
    name: 'Rust en Vrede Estate Potstill',
    fullName: 'Rust en Vrede Estate Potstill Brandy 750 ML',
    category: 'Brandy',
    origin: 'Stellenbosch, South Africa',
    price: 'R1625',
    image: '/assets/products/brandy/rust-en-vrede-potstill.png',
    badge: 'Estate reserve',
    brand: 'Rust en Vrede',
    size: '750 ML',
    sku: 'GSNGFWK0091',
    featured: false,
    options: ['Single bottle'],
    description: 'Estate-grown Cabernet Sauvignon, copper distilled and matured in French oak, with candied orange, toffee, vanilla and a silky finish.',
    details: { style: 'Estate potstill brandy', region: 'Stellenbosch, South Africa', maturation: 'Minimum 12 years in French oak', base: 'Cabernet Sauvignon' },
    tags: ['Brandy', 'Potstill', 'Stellenbosch'],
  },
  {
    id: 101,
    slug: 'chateau-margaux-premier-grand-cru-classe',
    name: 'Château Margaux 2015',
    fullName: 'Château Margaux Premier Grand Cru Classé 2015 750 ML',
    category: 'Wine',
    origin: 'Bordeaux, France',
    country: 'France',
    price: 'R21500',
    image: '/assets/products/chateau-margaux.png',
    badge: 'Iconic',
    brand: 'Château Margaux',
    size: '750 ML',
    sku: 'GS-FR-MARG-2015',
    description: 'A masterpiece of balance, elegance and power, expressing the unique terroir of Margaux with floral aromas, dense dark fruit and incredibly fine tannins.',
    details: { style: 'Bordeaux Blend', region: 'Bordeaux, France', vintage: '2015' }
  },
  {
    id: 102,
    slug: 'antinori-tignanello',
    name: 'Antinori Tignanello 2019',
    fullName: 'Marchesi Antinori Tignanello 2019 750 ML',
    category: 'Wine',
    origin: 'Tuscany, Italy',
    country: 'Italy',
    price: 'R4200',
    image: '/assets/products/tignanello.png',
    badge: 'Super Tuscan',
    brand: 'Marchesi Antinori',
    size: '750 ML',
    sku: 'GS-IT-TIG-2019',
    description: 'The pioneering Super Tuscan. A blend of Sangiovese, Cabernet Sauvignon and Cabernet Franc, delivering vibrant red fruit, spice and velvety texture.',
    details: { style: 'Super Tuscan Blend', region: 'Tuscany, Italy', vintage: '2019' }
  },
  {
    id: 103,
    slug: 'vega-sicilia-unico',
    name: 'Vega Sicilia Único 2013',
    fullName: 'Vega Sicilia Único 2013 750 ML',
    category: 'Wine',
    origin: 'Ribera del Duero, Spain',
    country: 'Spain',
    price: 'R11500',
    image: '/assets/products/vega-sicilia.png',
    badge: 'Legendary',
    brand: 'Vega Sicilia',
    size: '750 ML',
    sku: 'GS-SP-VSU-2013',
    description: 'Spain’s most prestigious wine. Aged extensively before release, it offers extraordinary complexity, with notes of dried fruit, tobacco, cedar and profound depth.',
    details: { style: 'Tempranillo Blend', region: 'Ribera del Duero, Spain', vintage: '2013' }
  },
  {
    id: 104,
    slug: 'penfolds-grange',
    name: 'Penfolds Grange 2018',
    fullName: 'Penfolds Grange 2018 Shiraz 750 ML',
    category: 'Wine',
    origin: 'South Australia',
    country: 'Australia',
    price: 'R15900',
    image: '/assets/products/penfolds-grange.png',
    badge: 'Cellar pick',
    brand: 'Penfolds',
    size: '750 ML',
    sku: 'GS-AU-PEN-2018',
    description: 'Australia’s most iconic Shiraz. Powerfully structured with intense dark plum, liquorice, mocha and American oak spice, built to age for decades.',
    details: { style: 'Shiraz', region: 'South Australia', vintage: '2018' }
  }
];

export const brands = [
  { name: 'Blue Spot', image: '/assets/brands/blue-spot.png' },
  { name: 'Tamnavulin', image: '/assets/brands/tamnavulin.png' },
  { name: 'Courvoisier', image: '/assets/brands/courvoisier.png' },
  { name: 'Bowmore', image: '/assets/brands/bowmore.png' },
  { name: 'Loch Lomond', image: '/assets/brands/loch-lomond.png' },
  { name: 'Scottish Leader', image: '/assets/brands/scottish-leader.png' },
  { name: 'Auchentoshan', image: '/assets/brands/auchentoshan.png' },
  { name: 'Sexton', image: '/assets/brands/sexton.png' },
];

export const tequilaBrands = [
  { name: 'Jose Cuervo', image: '/assets/brands/tequila/jose-cuervo.png' },
  { name: '1800 Tequila', image: '/assets/brands/tequila/1800.png' },
  { name: 'Casamigos', image: '/assets/brands/tequila/casamigos.png' },
  { name: 'CÃ³digo 1530', image: '/assets/brands/tequila/codigo-1530.png' },
  { name: 'EspolÃ²n', image: '/assets/brands/tequila/espolon.png' },
  { name: 'Don Julio', image: '/assets/brands/tequila/don-julio.png' },
  { name: 'InsÃ³lito', image: '/assets/brands/tequila/insolito.png' },
  { name: 'Solento', image: '/assets/brands/tequila/solento.png' },
]

export const brandyBrands = [
  { name: 'Meukow', image: '/assets/brands/brandy/meukow.png' },
  { name: 'KWV', image: '/assets/brands/brandy/kwv.png' },
  { name: 'Rust en Vrede', image: '/assets/brands/brandy/rust-en-vrede.png' },
  { name: 'Bayede!', image: '/assets/brands/brandy/bayede.png' },
  { name: 'Avante', image: '/assets/brands/brandy/avante.png' },
  { name: 'Blomendahl', image: '/assets/brands/brandy/blomendahl.png' },
  { name: 'Joseph Barry', image: '/assets/brands/brandy/joseph-barry.png' },
  { name: 'Oude Molen', image: '/assets/brands/brandy/oude-molen.png' },
]

export const menuCategories = [
  {
    name: 'Whisky',
    description: 'From smoky Islay to Japanese precision.',
    groups: [
      { title: 'By style', items: ['Single malt', 'Blended whisky', 'Single pot still', 'Single barrel'] },
      { title: 'By region', items: ['Scotland', 'Ireland', 'Japan', 'United States'] },
      { title: 'Collectors', items: ['Rare releases', 'Aged 18+ years', 'Gift editions', 'Cask strength'] },
    ],
  },
  {
    name: 'Wine',
    description: 'Cellar-worthy bottles from celebrated estates.',
    groups: [
      { title: 'By style', items: ['Red wine', 'White wine', 'RosÃ©', 'Fortified'] },
      { title: 'Sparkling', items: ['Champagne', 'Prosecco', 'Cap Classique', 'Cava'] },
      { title: 'Collections', items: ['South African icons', 'Old World', 'New World', 'Organic'] },
    ],
  },
  {
    name: 'Cognac & Brandy',
    description: 'Distinguished eaux-de-vie, patiently matured.',
    groups: [
      { title: 'Cognac', items: ['VS', 'VSOP', 'XO', 'Prestige cuvÃ©e'] },
      { title: 'Brandy', items: ['Cape potstill', 'French brandy', 'Armagnac', 'Fruit brandy'] },
      { title: 'Occasion', items: ['After dinner', 'Milestone gifts', 'Cocktail cabinet', 'Collector sets'] },
    ],
  },
  {
    name: 'Tequila & Mezcal',
    description: 'Estate-grown agave with genuine provenance.',
    groups: [
      { title: 'Tequila', items: ['Blanco', 'Reposado', 'AÃ±ejo', 'Cristalino'] },
      { title: 'Mezcal', items: ['EspadÃ­n', 'Ensamble', 'Wild agave', 'Ancestral'] },
      { title: 'Curated', items: ['Additive free', 'Single estate', 'Small batch', 'Gift sets'] },
    ],
  },
  {
    name: 'Gin, Rum & More',
    description: 'A considered cabinet of essential spirits.',
    groups: [
      { title: 'Gin', items: ['London dry', 'Contemporary', 'Pink gin', 'Navy strength'] },
      { title: 'Rum', items: ['Dark rum', 'Aged rum', 'Rhum agricole', 'Spiced rum'] },
      { title: 'Explore more', items: ['Vodka', 'Liqueur', 'Aperitifs', 'Non-alcoholic'] },
    ],
  },
  {
    name: 'Accessories',
    description: 'Considered tools and finishing touches for the home bar.',
    groups: [
      { title: 'Glassware', items: ['Whisky tumblers', 'Wine glasses', 'Champagne coupes', 'Tasting sets'] },
      { title: 'Barware', items: ['Decanters', 'Bottle openers', 'Cocktail tools', 'Ice accessories'] },
      { title: 'Gifting', items: ['Presentation boxes', 'Gift bags', 'Personalised notes', 'Collector displays'] },
    ],
  },
]

export const getProductPrice = (price) => Number(String(price).replace(/[^0-9.]/g, '')) || 0;
export const formatCartPrice = (value) => `R ${Math.round(value).toLocaleString('en-ZA', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;

export const auctionLots = [
  {
    lot: '039',
    title: 'Yamazaki 18 Year Old Single Malt',
    category: 'Japanese',
    image: '/assets/auction/yamazaki-lot.jpg',
    bid: 20700,
    bids: 25,
    offset: 0,
  },
  {
    lot: '042',
    title: 'Glenlivet 25 Year Old Single Malt',
    category: 'Scotch',
    image: '/assets/auction/glenlivet-lot.jpg',
    bid: 7292,
    bids: 9,
    offset: 68000000,
  },
  {
    lot: '052',
    title: 'Highland Park 21 Year Old Single Malt',
    category: 'Scotch',
    image: '/assets/auction/highland-lot.jpg',
    bid: 3250,
    bids: 6,
    offset: 246000000,
  },
];

export const pastAuctionLots = [
  { ...auctionLots[0], title: 'Yamazaki 18 Year Old Japanese Whisky', result: 'R20,700' },
  { ...auctionLots[1], result: 'R7,292' },
  { ...auctionLots[2], result: 'R3,250' },
  { lot: '061', title: 'Hibiki 17 Year Old Japanese Whisky', category: 'Japanese', image: '/assets/auction/hibiki-17.jpeg', result: 'R14,500' },
];

export const tastingEvents = [
  {
    id: 'whisky-six-countries',
    title: 'Whisky: Six Countries, Six Styles',
    type: 'Whisky',
    status: 'live',
    price: 600,
    seats: 19,
    image: '/assets/tastings/whisky-tasting.png',
    description: 'A guided flight through six celebrated whisky-making countries, exploring regional character, cask influence and the stories behind every pour.',
    dates: [
      { date: '2026-08-22', label: 'Saturday, 22 August', times: ['16:00', '18:30'] },
      { date: '2026-08-29', label: 'Saturday, 29 August', times: ['15:00', '17:30'] },
    ],
  },
  {
    id: 'cape-brandy-masterclass',
    title: 'Cape Brandy Masterclass',
    type: 'Brandy',
    status: 'live',
    price: 520,
    seats: 12,
    image: '/assets/blogs/south-african-brandy-brands.jpeg',
    description: 'Discover South African potstill heritage through mature Cape brandies, guided nosing and considered food pairings.',
    dates: [
      { date: '2026-09-05', label: 'Saturday, 5 September', times: ['16:30', '19:00'] },
      { date: '2026-09-12', label: 'Saturday, 12 September', times: ['17:00'] },
    ],
  },
  {
    id: 'agave-after-dark',
    title: 'Agave After Dark',
    type: 'Tequila',
    status: 'live',
    price: 680,
    seats: 8,
    image: '/assets/products/tequila/codigo-reposado.png',
    description: 'A focused tasting of blanco, reposado and añejo expressions, served with citrus, spice and a contemporary Mexican pairing menu.',
    dates: [
      { date: '2026-09-19', label: 'Saturday, 19 September', times: ['18:00', '20:00'] },
    ],
  },
  {
    id: 'islay-smoke-session',
    title: 'An Evening on Islay',
    type: 'Whisky',
    status: 'past',
    price: 750,
    seats: 0,
    image: '/assets/products/bowmore-gallery-1.png',
    description: 'A completed private session exploring peat, maritime maturation and the layered character of Islay single malt.',
    dates: [],
  },
];

export const brandyArticleBrands = [
  ['Klipdrift', 'The nation’s favourite', 'Distilled in Robertson and matured for at least three years, Klipdrift brings dried fruit, caramel and oak to an easy, generous style.'],
  ['Van Ryn’s', 'Award-winning luxury', 'A Stellenbosch benchmark known for long oak maturation, remarkable smoothness and vintage expressions made for important occasions.'],
  ['Oude Molen', 'Time-honoured tradition', 'More than a century of distilling informs a balanced house style, with VSOP bottlings shaped by warm vanilla and spice.'],
  ['Boplaas', 'Brandy with heritage', 'This family-run Calitzdorp distillery favours small batches, patient maturation, dried fruit and toasted-oak complexity.'],
  ['Tokara', 'Excellence in every sip', 'Tokara’s XO Potstill Brandy applies the estate’s exacting wine philosophy to a deep, intricate and elegant spirit.'],
  ['Joseph Barry', 'Small-batch perfection', 'Traditional distillation and a minimum of ten years in oak give the Joseph Barry XO Cape Brandy its composed, layered character.'],
  ['KWV', 'A South African classic', 'A name synonymous with local brandy, KWV is loved for full-bodied fruit, caramel and warming spice across its aged range.'],
  ['Imoya', 'A hidden gem', 'Aged components of up to twenty years reveal dark chocolate, dried fruit and a nutty, impeccably smooth finish.'],
  ['Oude Meester', 'A refined taste', 'Versatile and polished, Oude Meester offers a smooth house style equally suited to slow sipping and elevated serves.'],
  ['Wellington VO', 'Smooth and approachable', 'An accessible, easy-drinking brandy for relaxed evenings, generous highballs and classic cocktails.'],
];

export const premiumLiquorItems = [
  ['Glenfiddich 18-Year-Old Single Malt Scotch', 'Glenfiddich is known globally for its commitment to quality and heritage. The 18-Year-Old expression is a complex, matured single malt aged in Oloroso sherry and bourbon casks. For whisky lovers looking to elevate their home bar, this smooth and rich Scotch is a fantastic option when you shop alcohol online via The Grand Store.'],
  ['Belvedere Vodka', 'Luxury and purity meet in this Polish vodka made from 100% rye and distilled using artisanal techniques. Belvedere is perfect for a chilled martini or a classy cocktail night. Thanks to the online liqueur store setup of The Grand Store, you can now stock your shelf with this iconic vodka without stepping out.'],
  ['Hennessy V.S Cognac', 'Few names command respect in the liquor world like Hennessy. The V.S (Very Special) Cognac is bold, rich, and packs a flavourful punch—great for sipping neat or enjoying in a premium cocktail. It’s one of the top picks on The Grand Store, and a must-try for any connoisseur.'],
  ['Don Julio Reposado Tequila', 'Smooth, sophisticated, and surprisingly sippable—Don Julio Reposado is aged for eight months in American white-oak barrels, giving it a rounded finish and subtle complexity. This Mexican treasure is now just a few clicks away at The Grand Store, your go-to online liqueur store in South Africa.'],
  ['KWV 10-Year-Old Brandy', 'A true South African classic, KWV’s 10-Year-Old Brandy is internationally acclaimed for good reason. It’s rich, deep, and beautifully crafted. If you’re looking to support local while enjoying world-class quality, buying this brandy online from The Grand Store is a brilliant idea.'],
  ['Moët & Chandon Brut Imperial Champagne', 'Looking to celebrate in style? This iconic Champagne never goes out of fashion. With its balanced blend of Pinot Noir, Chardonnay, and Meunier grapes, Moët Brut is the epitome of celebration. And yes—you can shop alcohol online for your next toast without having to hit the store.'],
  ['Hendrick’s Gin', 'Hendrick’s isn’t just any gin—it’s a unique infusion of rose and cucumber, creating a signature floral and crisp profile that gin lovers absolutely adore. Whether it’s for a summer G&T or a bold cocktail creation, Hendrick’s is a standout at The Grand Store, ready for next-day delivery.'],
  ['Bains Cape Mountain Whisky', 'Crafted right here in South Africa, Bains is a proudly local single grain whisky that has won several global awards. It’s smooth, slightly sweet, and offers incredible value. If you’re exploring premium liquors on a budget, this is a hidden gem you can find on The Grand Store’s online shelves.'],
  ['Grey Goose Vodka', 'Imported from France, Grey Goose is known for its ultra-premium distillation and clean, crisp finish. Whether you’re making a martini or sipping it neat, Grey Goose delivers sophistication in every pour. The best part? You can shop alcohol online from the comfort of home at The Grand Store.'],
  ['Amarula Cream Liqueur', 'No South African liquor list is complete without Amarula. Made from the fruit of the indigenous marula tree and blended with cream, this liqueur is sweet, smooth, and a true taste of Africa. It’s perfect for after-dinner indulgence or mixing into coffee. Find this proudly local favorite easily at The Grand Store, your trusted online liqueur store.'],
];
